export const MEDICINES_LIST = [
  "Paracetamol 500mg / Dolo 650",
  "Amoxicillin 500mg",
  "Azithromycin 500mg",
  "Ibuprofen 400mg",
  "Metformin 500mg",
  "Atorvastatin 10mg",
  "Omeprazole 20mg",
  "Pantoprazole 40mg",
  "Cetirizine 10mg",
  "Ciprofloxacin 500mg",
  "Amlodipine 5mg",
  "Losartan 50mg",
  "Lisinopril 10mg",
  "Aspirin 75mg / 150mg",
  "Gabapentin 300mg",
  "Prednisone 10mg",
  "Montelukast 10mg",
  "Amoxicillin-Clavulanate 625mg",
  "Hydrochlorothiazide 12.5mg",
  "Doxycycline 100mg",
  "Furosemide 40mg",
  "Tramadol 50mg",
  "Sertraline 50mg",
  "Levothyroxine 50mcg",
  "Alprazolam 0.25mg",
  "Clonazepam 0.5mg",
  "Lorazepam 1mg",
  "Fluoxetine 20mg",
  "Escitalopram 10mg",
  "Metoprolol 25mg",
  "Carvedilol 6.25mg",
  "Rosuvastatin 10mg",
  "Simvastatin 20mg",
  "Clopidogrel 75mg",
  "Salbutamol Inhaler (100mcg)",
  "Tiotropium Inhaler",
  "Budesonide Respules 0.5mg",
  "Fluticasone Furoate Nasal Spray",
  "Ondansetron 4mg",
  "Domperidone 10mg",
  "Famotidine 20mg",
  "Sucralfate Syrup (10ml)",
  "Loperamide 2mg",
  "Antacid Gel (20ml)",
  "Metronidazole 400mg",
  "Clindamycin 300mg",
  "Erythromycin 500mg",
  "Clarithromycin 500mg",
  "Ceftriaxone Injection 1g",
  "Cefixime 200mg",
  "Cefuroxime 500mg",
  "Cefalexin 500mg",
  "Levofloxacin 500mg",
  "Ofloxacin 200mg",
  "Nitrofurantoin 100mg",
  "Fluconazole 150mg",
  "Itraconazole 100mg",
  "Ketoconazole Cream 2%",
  "Terbinafine 250mg",
  "Acyclovir 400mg",
  "Valacyclovir 500mg",
  "Oseltamivir 75mg",
  "Hydrocortisone 100mg",
  "Dexamethasone 4mg",
  "Betamethasone Ointment",
  "Triamcinolone Cream",
  "Diclofenac Sodium 50mg",
  "Aceclofenac 100mg",
  "Ketorolac 10mg",
  "Naproxen 500mg",
  "Mefenamic Acid 500mg",
  "Paracetamol + Tramadol",
  "Baclofen 10mg",
  "Tizanidine 2mg",
  "Cyclobenzaprine 10mg",
  "Sumatriptan 50mg",
  "Zolpidem 5mg",
  "Melatonin 3mg",
  "Ferrous Sulfate (Iron 60mg)",
  "Calcium Carbonate + Vitamin D3",
  "Vitamin B-Complex (Becosules)",
  "Vitamin C 500mg (Celin)",
  "Zinc Sulphate 20mg",
  "Folic Acid 5mg",
  "Multivitamin Softgels",
  "ORS Sachet (Oral Rehydration)",
  "Cough Syrup (Benadryl/Ascoril)",
  "Eye Drops (Tobramycin 0.3%)",
  "Ear Drops (Ofloxacin + Beclomethasone)",
  "Betadine Ointment 5%",
  "Human Insulin 40IU/ml",
  "Metformin + Sitagliptin",
  "Glimepiride 1mg / 2mg",
  "Teneligliptin 20mg",
  "Telmisartan 40mg",
  "Ramipril 2.5mg",
  "Nifedipine 10mg",
  "Diltiazem 30mg"
];

export const DOSAGE_OPTIONS = [
  "500 mg",
  "250 mg",
  "650 mg",
  "100 mg",
  "50 mg",
  "20 mg",
  "10 mg",
  "5 mg",
  "1 tablet",
  "2 tablets",
  "1 capsule",
  "5 ml",
  "10 ml",
  "1 puff / 2 puffs",
  "As directed"
];

export const FREQUENCY_OPTIONS = [
  "Once a day (1-0-0) - Morning",
  "Once a day (0-0-1) - Night",
  "Twice a day (1-0-1) - Morning & Night",
  "Thrice a day (1-1-1) - Morning, Afternoon & Night",
  "Four times a day (1-1-1-1)",
  "Every 8 hours",
  "Before food (Ac)",
  "After food (Pc)",
  "As needed (PRN) for pain/fever"
];

export const DURATION_OPTIONS = [
  "3 days",
  "5 days",
  "7 days",
  "10 days",
  "14 days",
  "1 month",
  "3 months",
  "Until next review",
  "As needed"
];
